environment=[
'Acetaldehyde',
 'Acetamide',
 'Acetic Acid',
 'Chlorine',
 'Formic Acid',
 'Acetic Anhydride',
 'Acetochloride',
 'Acetone',
 'Aluminum Chloride',
 'Acetosalicylic Acid',
 'Adipic Acid',
 'Aluminum Acetate',
 'Aluminum Ammonium Sulfate',
 'Aluminum Fluoride',
 'Aluminum Hydroxide',
 'Aluminum Nitrate',
 'Aluminum Sulfate',
 'Aminoacetic Acid',
 'Ammonia',
 'Ammonium Bicarbonate',
 'Ammonium Bifluoride',
 'Ammonium Bisulfate',
 'Ammonium Carbonate',
 'Hydrochloric Acid',
 'Ammonium Hydroxide',
 'Ammonium Chloride',
 'Ammonium Sulfate',
 'Sodium Hydroxide',
 'Ammonium Fluoride',
 'Ammonium Hexachlorostannate',
 'Ammonium Nitrate',
 'Ammonium Oxalate',
 'Sulfuric Acid',
 'Ammonium Perchlorate',
 'Ammonium Phosphate',
 'Ammonium Sulfite',
 'Aniline',
 'Aniline Hydrochloride',
 'Antimony Chloride',
 'Aqua Regia',
 'Arsenic Acid',
 'Atmospheric Environments',
 'Barium Chloride',
 'Barium Carbonate',
 'Barium Chloride Dihydrate',
 'Barium Hydroxide',
 'Benzole',
 'Barium Nitrate',
 'Benzene',
 'Benzoic Acid',
 'Blood',
 'Boric Acid',
 'Bromine',
 'Butane',
 'Butyric Acid',
 'Butyl Alcohol',
 'Cadmium Sulfate',
 'Calcium Bisulfite',
 'Calcium Bromide',
 'Calcium Chloride',
 'Camphor',
 'Calcium Fluoride',
 'Calcium Hydroxide',
 'Calcium Hypochloride',
 'Calcium Hypochlorite',
 'Calcium Sulfate',
 'Calcium Sulfite',
 'Caprylic Acid',
 'Carbon',
 'Carbon Bisulfide',
 'Carbon Dioxide',
 'Chloric Acid',
 'Carbon Disulfide',
 'Carbon Monoxide',
 'Carbon Tetrachloride',
 'Carbonic Acid',
 'Carnallite',
 'Chlorine Dioxide',
 'Chlorine Water',
 'Chloroacetic Acid',
 'Chlorobenzene',
 'Citric Acid',
 'Chloroform',
 'Chlorosulfonic Acid',
 'Chrome Sulfate',
 'Chromic Acid',
 'Copals',
 'Copper Carbonate',
 'Creosote',
 'Cresol',
 'Cupric Chloride',
 'Cupric Nitrate',
 'Ethyl Alcohol',
 'Cupric Sulfate',
 'Cuprous Acetate',
 'Cuprous Chloride',
 'Cuprous Cyanide',
 'Cuprous Nitrate',
 'Cuprous Sulfate',
 'Detergent',
 'Dichloroacetic Acid',
 'Dichloroethane',
 'Dichloroethylene',
 'Diethyl Ether',
 'Disulfur Dichloride',
 'Fatty Acid',
 'Ether',
 'Ethyl Chloride',
 'Ethyl Glycol',
 'Ethylene Glycol',
 'Ferric Chloride',
 'Fluorine',
 'Ferric Nitrate',
 'Ferric Sulfate',
 'Ferrous Chloride',
 'Ferrous Sulfate',
 'Fertilizers',
 'Food Products',
 'Flue Gas',
 'Formaldehyde',
 'Fluosilicic Acid',
 'Glycerol',
 'Fruit Juices',
 'Gallic Acid',
 'Gasoline',
 'Gelatin',
 'Gluconic Acid',
 'Glue (also acid)',
 'Glycerine',
 'Hydrazine Sulfate',
 'Hydrobromic Acid',
 'Hydrofluoric Acid',
 'Hydrocyanic Acid',
 'Hydrogen',
 'Hydrogen Chloride',
 'Hydrogen Cyanide',
 'Hydrogen Fluoride',
 'Hydrogen Peroxide',
 'Hydrogen Sulfide',
 'Hydroiodic Acid',
 'Hydroxylamine Sulfate',
 'Hypochlorites',
 'Hypochlorous Acid',
 'Iodine',
 'Iron Phosphate',
 'Lactic Acid',
 'Lead Acetate',
 'Lead Nitrate',
 'Linseed Oil',
 'Liquid Metals',
 'Lodoform',
 'Liquid metals',
 'Lithium Bromide',
 'Mercuric Chloride',
 'Lithium Chloride',
 'Lithium Hydride',
 'Lithium Hydroxide',
 'Lubricating Oil',
 'Magnesium Bromide',
 'Magnesium Carbonate',
 'Magnesium Chloride',
 'Nitric Acid',
 'Magnesium Hydroxide',
 'Magnesium Perchlorate',
 'Magnesium Sulfate',
 'Maleic Acid',
 'Malic Acid',
 'Manganese Chloride',
 'Manganese Sulfate',
 'Mercuric Acetate',
 'Mercuric Cyanide',
 'Mercurous Nitrate',
 'Methyl Alcohol',
 'Methyl Chloride',
 'Methylene Chloride',
 'Monochloroacetic Acid',
 'Nickel Chloride',
 'Nickel Nitrate',
 'Nickel Sulfate',
 'Nitric Oxide',
 'Nitric Tetroxide',
 'Nitrogen',
 'Nitrosylsulfuric Acid',
 'Nitrous Acid',
 'Oleic Acid',
 'Oxalic Acid',
 'Oxygen',
 'Ozone',
 'Phenol',
 'p-Toluene Sulfonchloramide Sodium',
 'Paraffin',
 'Perchloric Acid',
 'Petroleum Naphtha',
 'Petroleum Oils',
 'Phosphoric Acid',
 'Phosgene',
 'Phosphorus',
 'Picric Acid',
 'Polythionic Acid',
 'Potassium Acetate',
 'Seawater',
 'Potassium Aluminum Sulfate',
 'Potassium Bisulfate',
 'Potassium Bitartrate',
 'Potassium Bromide',
 'Potassium Carbonate',
 'Potassium Chlorate',
 'Potassium Chloride',
 'Silver Chloride',
 'Potassium Chrome Sulfate',
 'Potassium Cyanate',
 'Potassium Cyanide',
 'Potassium Dichromate',
 'Potassium Difluoride',
 'Potassium Ferricyanide',
 'Potassium Ferrocyanide',
 'Potassium Fluoride',
 'Potassium Hydroxide',
 'Potassium Hypochlorite',
 'Potassium Iodide',
 'Potassium Nitrate',
 'Potassium Oxalate',
 'Potassium Permanganate',
 'Potassium Sulfate',
 'Potassium Thiocyanate',
 'Printing Ink',
 'Propionic Acid',
 'Quinine Sulfate',
 'Pyrogallic Acid',
 'Salicylic Acid',
 'Salt of Hartshorn',
 'Silver Bromide',
 'Silver Nitrate',
 'Soap',
 'Sodium',
 'Sodium Acetate',
 'Sodium Bicarbonate',
 'Sodium Hypochlorite',
 'Sodium Bisulfate',
 'Sodium Bisulfite',
 'Sodium Borate',
 'Sodium Bromide',
 'Sodium Carbonate',
 'Sodium Chlorate',
 'Sodium Chloride',
 'Sodium Nitrate',
 'Sodium Nitrite',
 'Sodium Chlorite',
 'Sodium Fluoride',
 'Sodium Hydrogen Phosphate',
 'Steam',
 'Sodium Perborate',
 'Sodium Perchlorate',
 'Sodium Peroxide',
 'Sodium Phosphate',
 'Sodium Salicylate',
 'Sodium Silicate',
 'Sodium Sulfate',
 'Sodium Sulfide',
 'Sodium Sulfite',
 'Sodium Tetraborate',
 'Sodium Thiosulfate',
 'Soil',
 'Stannic Chloride',
 'Stannous Chloride',
 'Stearic Acid',
 'Succinic Acid',
 'Sulfur',
 'Sulfur Dioxide',
 'Sulfur Trioxide',
 'Sulfurous Acid',
 'Tannic Acid',
 'Super Phosphate',
 'Tar',
 'Tartaric Acid',
 'Water',
 'Thioglycolic Acid',
 'Toluene',
 'Trichloroacetic Acid',
 'Trichloroethylene',
 'Turpentine',
 'Urea',
 'Vegetable Oil',
 'Viscose',
 'Xylene',
 'Zinc Chloride',
 'Zinc Cyanide',
 'Zinc Sulfate']
 
targets={'0':'< 0.002 inches/year','1':'< 0.020 inches/year','2':' 0.050 inches/year','3':'> 0.050 inches/year'}